spring.application.name=data-donation

server.servlet.context-path=/api

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/data-donation-db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# FILE UPLOADS
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Cloudflare & AWS R2
cloudflare.account.id=${CLOUDFLARE_ACCOUNT_ID}
aws.access.key.id=${AWS_ACCESS_KEY_ID}
aws.secret.access.key=${AWS_SECRET_ACCESS_KEY}
aws.s3.bucket=${AWS_S3_BUCKET:data-donation}
aws.s3.endpoint=https://${cloudflare.account.id}.r2.cloudflarestorage.com
aws.public.url=${AWS_PUBLIC_URL}

# JWT
application.security.jwt.secret=${JWT_ACCESS_SECRET}
application.security.jwt.token.secret=${JWT_REFRESH_SECRET}
application.security.jwt.access.expiration.minutes=30
application.security.jwt.refresh.expiration.days=30

